### ISSUE TITLE
Project S-11 crashes in the Game Over screen

### ISSUE THREAD

**Issue by Vidnez** [jduckett95/misc-pocket-patches#2]
Once you lose all your lives, the game crashes. I dont know if theres a Game Over screen or a Continue screen after that, lol.

**Comment by jduckett95** [comment]
I've passed it on to r0r0, they'll look at it when they can. In the meantime, just call it **hardcore mode** ;)

**Comment by jduckett95** [comment]
Fix released! https://github.com/jduckett95/misc-pocket-patches/blob/main/project-s-11-pocket-8fe6340c822daa9cb07c7d8ab8509751-v2.ips
