### ISSUE TITLE
Trip World crashes during ending cutscene

### ISSUE THREAD

**Issue by t3rminus** [jduckett95/misc-pocket-patches#3]
After beating the final boss, as the characters turn to face the background, the game freezes.

**Comment by JoseJX** [comment]
Could you please test the patch in the pull request above and let me know if it fixes the issue? It's untested, but I'm pretty sure it at least fixes a crash bug. I'm just not sure it fixes *that* crash bug!

**Comment by t3rminus** [comment]
Well, the crash is fixed, but the game **_really_** isn't happy about it. The cutscene appears extremely garbled for a few moments, but then transitions to the credits an appears to work fine after that. Photos attached.

![IMG_1392](https://user-images.githubusercontent.com/643473/153831510-3993a727-4559-4cdb-88c8-265a012ec90e.jpeg)
![IMG_1393](https://user-images.githubusercontent.com/643473/153831517-492ae760-3b17-4cf4-a020-1497c23050cd.jpeg)

**Comment by JoseJX** [comment]
Progress! It looks like there's a missing STAT instruction as well. Would it be possible for you to play the game in an emulator and generate a save state right before the credit scene? Emulicious can play the .pocket file, so I'd recommend that if possible. If not, a save state from any emulator would be fine as well.  It's much easier to debug when I can reproduce it myself!

Thanks again for testing!

**Comment by t3rminus** [comment]
Save state attached. It's about 30-ish seconds before the game gets garbled.

For some reason, using a save state in Emulicious broke the sound playback. Not sure why, but the game just started producing a low hum instead of any music or sound. Didn't seem to affect anything else though.

[Trip World.sn0.zip](https://github.com/jduckett95/misc-pocket-patches/files/8063595/Trip.World.sn0.zip)

**Comment by JoseJX** [comment]
Not a problem, should be enough to figure it out later tonight. Thanks a bunch, this really makes it a lot easier to troubleshoot.

**Comment by JoseJX** [comment]
Sorry, I need to re-open this, I haven't fixed the other corruption yet. I'll try to get to it today.

**Comment by JoseJX** [comment]
Okay, I think this is resolved now in [my branch, in this pull request](https://github.com/jduckett95/misc-pocket-patches/pull/6)! If you could please test and report, I'd appreciate it! Thanks for reporting!

**Comment by t3rminus** [comment]
I completed the game on the Pocket with no issues! Thanks so much for fixing this. Such a fun little diversion of a game.

**Comment by JoseJX** [comment]
No problem, glad it worked for you :)
